---
- hosts: linux
  vars:
    - root_password: ''
  sudo: true
  tasks:
    - name: Change the root user's password
      user:
        name=root
        password={{ root_password }}
    - name: Add new user remote
      user:
        name=remote
        password={{ root_password }}

    - name: Allow root SSH access
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp="^PermitRootLogin"
        line="PermitRootLogin yes"
        state=present
      notify:
        - restart sshd

    - name: Disallow SSH password authentication
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp="^PasswordAuthentication"
        line="PasswordAuthentication yes"
        state=present
      notify:
        - restart sshd
  handlers:
      - name: restart sshd
        service:
          name=sshd
          state=restarted
